[tool.poetry]
authors = ["Tobias Wohland <Tobias.Wohland@gmail.com>"]
description = "Logs upcoming validator duties to the console."
license = "MIT"
name = "eth-duties"
readme = "README.md"
repository = "https://github.com/TobiWo/eth-duties"
version = "0.2.0"

[tool.poetry.dependencies]
colorama = "==0.4.6"
dataclass-wizard = "==0.22.0"
eth-typing = "==3.2.0"
fastapi = "==0.97.0"
python = ">=3.10.0,<3.11"
pyyaml = "==6.0.1"
requests = "==2.28.1"
uvicorn = "==0.22.0"

[tool.poetry.group.dev.dependencies]
black = "==22.10.0"
isort = "==5.6.2"
mypy = "==0.982"
pyinstaller = "==4.10.0"
pylint = "==2.15.3"
rope = "==1.4.0"
types-PyYAML = "==6.0.12.11"
types-requests = "==2.28.11"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.isort]
profile = "black"
