[tool.poetry]
authors = ["Tobias Wohland <Tobias.Wohland@gmail.com>"]
description = "Logs upcoming validator duties to the console."
license = "MIT"
name = "eth-duties"
readme = "README.md"
repository = "https://github.com/TobiWo/eth-duties"
version = "0.4.0"

[tool.poetry.dependencies]
dataclass-wizard = "==0.22.0"
eth-typing = "==3.4.0"
fastapi = "==0.103.0"
python = ">=3.10.0,<3.11"
pyyaml = "==6.0.1"
requests = "==2.31.0"
sty = "==1.0.4"
uvicorn = "==0.23.2"

[tool.poetry.group.dev.dependencies]
black = "==23.7.0"
isort = "==5.12.0"
mypy = "==1.5.1"
pyinstaller = "==4.10.0"
pylint = "==2.17.5"
rope = "==1.4.0"
types-PyYAML = "==6.0.12.11"
types-requests = "==2.31.0.2"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.isort]
profile = "black"
