"""Defines json object names
"""

RESPONSE_JSON_DATA_FIELD_NAME = "data"
RESPONSE_JSON_DATA_GENESIS_TIME_FIELD_NAME = "genesis_time"
RESPONSE_JSON_STATUS_FIELD_NAME = "status"
RESPONSE_JSON_INDEX_FIELD_NAME = "index"
RESPONSE_JSON_VALIDATOR_FIELD_NAME = "validator"
RESPONSE_JSON_PUBKEY_FIELD_NAME = "pubkey"
RESPONSE_JSON_VALIDATING_PUBKEY_NAME = "validating_pubkey"
RESPONSE_JSON_MESSAGE_NAME = "message"
