"""Defines program related constants
"""

REQUEST_TIMEOUT = (3, 5)
REQUEST_CONNECTION_ERROR_WAITING_TIME = 2
REQUEST_READ_TIMEOUT_ERROR_WAITING_TIME = 5
REQUEST_HEADER = {"Content-type": "application/json", "Accept": "application/json"}
DUTY_LOGGING_TIME_FORMAT = "%M:%S"
THRESHOLD_TO_INFORM_USER_FOR_WAITING_PERIOD = 5000
NOT_ALLOWED_CHARACTERS_FOR_VALIDATOR_PARSING = [".", ","]
NUMBER_OF_VALIDATORS_PER_REST_CALL = 1000
MAX_NUMBER_OF_VALIDATORS_FOR_FETCHING_ATTESTATION_DUTIES = 100
ALIAS_SEPARATOR = ";"
PUBKEY_PREFIX = "0x"
PUBKEY_LENGTH = 48
SIZE_OF_SHARED_MEMORY = 10_000_000
UPDATED_SHARED_MEMORY_NAME = "updated"
ACTIVE_VALIDATOR_IDENTIFIERS_WITH_ALIAS_SHARED_MEMORY_NAME = (
    "shared_active_validator_identifiers_with_alias"
)
ACTIVE_VALIDATOR_IDENTIFIERS_SHARED_MEMORY_NAME = "shared_active_validator_identifiers"
ALL_VALIDATOR_IDENTIFIERS_SHARED_MEMORY_NAMES = [
    ACTIVE_VALIDATOR_IDENTIFIERS_SHARED_MEMORY_NAME,
    ACTIVE_VALIDATOR_IDENTIFIERS_WITH_ALIAS_SHARED_MEMORY_NAME,
]
