---
# This is an example/template compose to add eth-duties to your client deployments.
# It assumes that you created a docker network called 'ethereum'.
# In this example, if you e.g. update the beacon node image tag, the beacon node
# will only get updated when eth-duties exits gracefully.
# In this example eth-duties exits gracefully when no sync-committee or block proposal
# duties are in the queue.

version: "3.9"
name: "eth-duties-cicd-template"
services:
  eth-duties:
    container_name: "eth-duties"
    image: "tobiwo/eth-duties:<IMAGE_TAG>"
    command:
      - "--validators"
      - "1,3,5,7,9,10,12,124,45346,366"
      - "--beacon-node"
      - "http://<NAME_OF_YOUR_BEACON_NODE_CONTAINER>:<PORT_OF_BEACON_API>"
      - "--mode"
      - "cicd-wait"
      - "--omit-attestation-duties"
    networks:
      - "ethereum"

  beacon-node:
    image: "<IMAGE_PATH>:<IMAGE_TAG>"
    container_name: "beacon-node"
    command:
      - "--..."
    volumes:
      - "<HOST_PATH>:<CONTAINER_PATH>"
    stop_grace_period: "2m"
    restart: "always"
    depends_on:
      eth-duties:
        condition: "service_completed_successfully"
    networks:
      - "ethereum"

networks:
  ethereum:
    external: true
...
