---
# This is an example/template compose to add eth-duties to your present docker setup.
# It assumes that you created a docker network called 'ethereum'.
# Note: If you provide a validator with an alias you do not need to wrap this combined string
# in quotes or doubles quotes as you would do it while using the eth-duties binary
# on the command line or a docker run call (see example below)
# Note: You can use either space and/or comma separation for flag --validators

name: "eth-duties"
services:
  eth-duties:
    container_name: "eth-duties"
    image: "tobiwo/eth-duties:<IMAGE_TAG>"
    command:
      - "--validators"
      # yamllint disable-line rule:line-length
      - "123 456 0x8472eb896af6de1e3d614e9b8fead626120291d5067edf15961c3e7385a0299d09f7f94eb6bbf96e904e7caf390ffd2f 789;My_Validator"
      - "--validators"
      - "111,222,333"
      - "--beacon-node"
      - "http://<NAME_OF_YOUR_BEACON_NODE_CONTAINER>:<PORT_OF_BEACON_API>"
    networks:
      - "ethereum"
networks:
  ethereum:
    external: true
...
