FROM python:3.10-alpine3.15

COPY requirements.txt /tmp
WORKDIR /tmp
RUN python3 -m pip install --no-cache-dir -r requirements.txt

RUN adduser -D app
USER app

WORKDIR /home/app

COPY config ./config
COPY duties ./duties

ENTRYPOINT [ "python", "duties/main.py" ]
