FROM python:3.12.0-alpine3.18 AS python
ENV PYTHONUNBUFFERED=true
WORKDIR /home/app

FROM python AS poetry
ENV POETRY_HOME=/opt/poetry
ENV POETRY_VIRTUALENVS_IN_PROJECT=true
ENV PATH="$POETRY_HOME/bin:$PATH"
RUN python3 -m pip install --no-cache-dir poetry==1.7.1
COPY pyproject.toml .
COPY poetry.lock .
RUN poetry install --only main --no-interaction --no-root

FROM python AS runtime
LABEL author1="Tobias Wohland" \
  author2="Nils Effinghausen" \
  name="eth-duties" \
  description="Tool to log upcoming validator duties to the console."
ENV PATH="/home/app/.venv/bin:$PATH"
COPY --from=poetry /home/app /home/app
COPY config ./config
COPY duties ./duties
RUN adduser -D app
USER app
ENTRYPOINT [ "python", "duties/main.py" ]
