---
name: "Build and Push docker image"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - "main"
      - "develop"
    tags:
      - "v*.*.*"

jobs:
  build-docker-image-job:
    name: "Build and push docker image"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Extract metadata for image tags and labels"
        id: "meta"
        uses: "docker/metadata-action@v5"
        with:
          images: |
            ${{ secrets.DOCKER_REPOSITORY }}
          tags: |
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=develop,enable=${{ github.ref == 'refs/heads/develop' }}
      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@v3"
      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v3"
      - name: "Login to Docker Hub"
        uses: "docker/login-action@v3"
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
      - name: "Build and push image"
        uses: "docker/build-push-action@v6"
        with:
          file: "./docker/Dockerfile"
          context: "."
          platforms: "linux/amd64,linux/arm64"
          push: true
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels }}"
          cache-from: "type=gha"
          cache-to: "type=gha,mode=max"
...
