name: Create tag

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  tag:
    if: startsWith(github.event.pull_request.body, '/release')
    name: Create and push tag
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: none
        RELEASE_BRANCHES: main
        MAJOR_STRING_TOKEN: perf
        MINOR_STRING_TOKEN: feat
        PATCH_STRING_TOKEN: fix
        BRANCH_HISTORY: last
