name: semver

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: none
        RELEASE_BRANCHES: main
        MAJOR_STRING_TOKEN: perf
        MINOR_STRING_TOKEN: feat
        PATCH_STRING_TOKEN: fix
